### PR TITLE
Added "setdomain" option

### PR DESCRIPTION
**Pull request by ciyi**
"setdomain" option allows user to customize the domain name to be included in the generated database. This is useful to make more realistic demos with BloodHound.

### CODE REVIEW

**Comment by rvazarkar** [comment]
Can you use string formatting instead of concatenating strings? It's like a million times easier to read. 

```
group = "DOMAIN USERS@{}".format(self.domain)
```

**Comment by ciyi** [comment]
Then we'll need to escape every {} brace in Cypher queries by doubling it: {{ and }}. Not sure what whould be more confusing.

```
session.run('UNWIND {{props}} as prop MERGE (n:User {{name:prop.name}}) SET n += prop.props WITH n MERGE (m:Group {{name:"DOMAIN USERS@{}"}}) WITH n,m MERGE (n)-[:MemberOf]->(m)'.format(self.domain), props=props)
```
or 

```
group = "DOMAIN USERS@"{}.format(self.domain)
session.run('UNWIND {{props}} as prop MERGE (n:User {{name:prop.name}}) SET n += prop.props WITH n MERGE (m:Group {{name:"{}"}}) WITH n,m MERGE (n)-[:MemberOf]->(m)'.format(group), props=props)
```

What do you think? I'll be happy to do so if you prefer it.

**Comment by rvazarkar** [comment]
Instead of formatting names into the query, you can pass the name as a parameter to the cypher query

```
gname = "DOMAIN USERS@{}".format(self.domain)
session.run('UNWIND {props} as prop MERGE (n:User {name:prop.name}) SET n += prop.props WITH n MERGE (m:Group {name: {dn}}) WITH n,m MERGE (n)-[:MemberOf]->(m)', props=props, dn=gname)
```

This also ensure thats values are properly escaped instead of being interpreted as cypher strings

**Comment by ciyi** [comment]
Is there anything else I can help with? :)

**Comment by rvazarkar** [comment]
Resolved the conflicts, gonna test this later to make sure it works properly and then I'll merge it 👍

**Pull request merged**
